### ISSUE TITLE
Where to do?

### ISSUE THREAD

**Issue by MemorableUsername1** [SamueleAmato/SocialMediaHackingToolkit#11]
i met all the requirements + setup everything

what file do i open to enter "python3 igkit.py etc etc" and such commands

also when i try to open igkit.py file 
its always setup did not run properly would you like to try again

(side note incase this is the problem: when i tried to open whosys it said ill have to resave it or something like that)

**Comment by MemorableUsername1** [comment]
I should probably add it said something about my pyfiglet not being in my exe path ? Or something like that

**Comment by SamueleAmato** [comment]
you news ti install pyfiglet on Windows

**Comment by MemorableUsername1** [comment]
> you need ti install pyfiglet on Windows



> you need ti install pyfiglet on Windows

ive already got pyfiglet 
could this be because you removed setup_ver?

since it mentions in the code for igkit.py 
if systemis == "Windows":
     try: 
          from src.setup_ver import *
     except Exception:

(im on windows)

**Comment by SamueleAmato** [comment]
setup_ver I removed it because it is created when the setup is completed, this only happens on Linux, on Windows it has to be created manually in the SRC folder, I added this step to the setup, try creating the filesetup_verml.py in the SRC folder and it should work

**Comment by MemorableUsername1** [comment]
> setup_ver I removed it because it is created when the setup is completed, this only happens on Linux, on Windows it has to be created manually in the SRC folder, I added this step to the setup, try creating the filesetup_ver.py in the SRC folder and it should work

Anything I should put in the file? Could you tell me how to create said file too? Thanks 

Sorry for the trouble

**Comment by SamueleAmato** [comment]
open the src folder, create inside it a file called "setup_ver.py
(:
tell me if it works

**Comment by MemorableUsername1** [comment]
did I do this correctly? (there is nothing in the python file)
I tried but it still says setup did not run correctly



![screensh for github](https://user-images.githubusercontent.com/119705845/206783863-1d8bafcf-b696-41c8-b96d-ff608b60e931.png)

**Comment by SamueleAmato** [comment]
i updated the repository, clone and try again, tell me if now it work

**Comment by MemorableUsername1** [comment]
still gives me "setup did not run properly" but it displays all the commands 

setup_ver did add in so that was good

but in setup it said 'touch' is not recognized as an internal or external command,
operable program or batch file.    could that be the problem?

**Comment by MemorableUsername1** [comment]
> i updated the repository, clone and try again, tell me if now it work

still gives me "setup did not run properly" but it displays all the commands

setup_ver did add in so that was good

but in setup it said 'touch' is not recognized as an internal or external command,
operable program or batch file. could that be the problem?

**Comment by SamueleAmato** [comment]
tomorrow i test the program on a Windows PC and i try to fix the problem

**Comment by SamueleAmato** [comment]
try now

**Comment by MemorableUsername1** [comment]
> try now

still gives me setup did not run properly but displays all the commands
I have every module required

after i say im windows on setup and it checks my modules it does say this before it checks
"Defaulting to user installation because normal site-packages is not writeable"  but i don't think that is the issue

**Comment by SamueleAmato** [comment]
make sure you are using the latest version of python (3.0+) and try again, if the program gives the error again:
go to the src folder and open whosys.py, check if the variable "systemis" is equal to "Windows", if it is not, replace the whosys.py code with:

    systemis = "Windows"

if the program still returns an error:

open igkit.py and replace the following block of code:

    if systemis == "Windows":
         try: 
              from src.setup_ver import *
         exception: exception:
              choice_setup = input("Setup failed, do you want to run it again? [y/n]: ")
              if choice_setup == "y":
                   os.chdir("src")
                   os.system("python3 setup.py")
                   exit()
              elif choice_setup == "n":
                   exit()

with:

    from src.setup_ver import *

tell me the output error
